services:
  backend:
    build: .
    container_name: inventory-api-dev
    command: sleep infinity
    env_file:
    - .env
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true
  db:
    image: postgres:17
    container_name: inventory-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
